[package]
name = "rbuild"
version = "0.3.0"
authors = ["Pranav Marathe <pmarathe25@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Rust-based build system"
repository = "https://github.com/pmarathe25/RBuild"

[dependencies]
paragraphs = ">= 0.3.1"
rgparse = ">= 0.1.2"
